"""create event infrastructure

Revision ID: c8edab41d87f
Revises: 
Create Date: 2026-08-18 21:26:04.359652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8edab41d87f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_event_id', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='received', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_event_id', name='uq_intelligence_events_source_event')
    )
    op.create_index(op.f('ix_intelligence_events_correlation_id'), 'intelligence_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_intelligence_events_entity_id'), 'intelligence_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_intelligence_events_entity_type'), 'intelligence_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_intelligence_events_event_id'), 'intelligence_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_intelligence_events_event_type'), 'intelligence_events', ['event_type'], unique=False)
    op.create_index('ix_intelligence_events_event_type_occurred_at', 'intelligence_events', ['event_type', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_intelligence_events_occurred_at'), 'intelligence_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_intelligence_events_source'), 'intelligence_events', ['source'], unique=False)
    op.create_index(op.f('ix_intelligence_events_status'), 'intelligence_events', ['status'], unique=False)
    op.create_table('outbox_events',
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_type'), 'outbox_events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_available_at'), 'outbox_events', ['available_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_available_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_intelligence_events_status'), table_name='intelligence_events')
    op.drop_index(op.f('ix_intelligence_events_source'), table_name='intelligence_events')
    op.drop_index(op.f('ix_intelligence_events_occurred_at'), table_name='intelligence_events')
    op.drop_index('ix_intelligence_events_event_type_occurred_at', table_name='intelligence_events')
    op.drop_index(op.f('ix_intelligence_events_event_type'), table_name='intelligence_events')
    op.drop_index(op.f('ix_intelligence_events_event_id'), table_name='intelligence_events')
    op.drop_index(op.f('ix_intelligence_events_entity_type'), table_name='intelligence_events')
    op.drop_index(op.f('ix_intelligence_events_entity_id'), table_name='intelligence_events')
    op.drop_index(op.f('ix_intelligence_events_correlation_id'), table_name='intelligence_events')
    op.drop_table('intelligence_events')
    # ### end Alembic commands ###
